#!/bin/bash

# Ansi color code variables
red="\e[0;91m"
green="\e[0;92m"
white="\e[0;97m"

#Tout s'est bien passé
exit_value=0

function resultGeneration {
    path=$1/decompile
    file_src=$2
    file_name=$3

    #generation du premier resultat
    decac -p $file_src > $path/generated/$file_name"1".deca
    res1_file=$path/generated/$file_name"1".deca

    #generation du deuxieme resultat
    decac -p $res1_file > $path/generated/$file_name"2".deca
    res2_file=$path/generated/$file_name"2".deca

	#On compare les fichiers
    if cmp -s $res1_file $res2_file; then
		echo -e "${green} ${bold} PASSED $file_name ${reset}"
        rm $res1_file
        rm $res2_file
	else
		exit_value=1
		echo -e "${red} ${bold} FAILED $file_name ${reset}"
	fi
}


folder_path=./src/test/deca/syntax/valid

# Creation de la hierarchie de dossier
mkdir -p $folder_path/decompile
mkdir -p $folder_path/decompile/provided
mkdir -p $folder_path/decompile/generated

generic_test=$folder_path/provided
specific_test=$folder_path/decompile/provided


#for file_src in $specific_test/*.deca; do
#
#    #nom du fichier
#    file_name=${file_src##$specific_test}
#    file_name=${file_name%%".deca"}
#
#    resultGeneration $folder_path $file_src $file_name
#done


for file_src in $generic_test/*.deca; do

    #nom du fichier
    file_name=${file_src##$generic_test/}
    file_name=${file_name%%".deca"}

    resultGeneration $folder_path $file_src $file_name
done
